FIND_PATH(MUGGLEC_INCLUDE_DIR
	NAMES muggle/c/muggle_c.h
	PATH_SUFFIXES include
	PATHS ${CMAKE_PREFIX_PATH})

FIND_LIBRARY(MUGGLEC_LIBRARIES
	NAMES mugglec
	PATHS ${CMAKE_PREFIX_PATH})

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MUGGLEC DEFAULT_MSG
    MUGGLEC_INCLUDE_DIR
	MUGGLEC_LIBRARIES)
